// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("MassTransit.RavenDbIntegration")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2016 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("3.3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.3.0.0")]
[assembly: AssemblyInformationalVersionAttribute("3.3.0-unstable.14+Branch.develop.Sha.cb77d3d8155e2379d2d0a995f2b3df3a309dde78")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.3.0.0";
        internal const string InformationalVersion = "3.3.0-unstable.14+Branch.develop.Sha.cb77d3d8155e2379d2d0a995f2b3df3a309dde78";
    }
}
