// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("MassTransit.RavenDbIntegration")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2016 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("3.3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.3.0.0")]
[assembly: AssemblyInformationalVersionAttribute("3.3.0-unstable.8+Branch.develop.Sha.1a3cbca0b385a235171389506aacf1631923d6d9")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.3.0.0";
        internal const string InformationalVersion = "3.3.0-unstable.8+Branch.develop.Sha.1a3cbca0b385a235171389506aacf1631923d6d9";
    }
}
