// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("masstransit")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2018 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("3.5.7.0")]
[assembly: AssemblyFileVersionAttribute("3.5.7.0")]
[assembly: AssemblyInformationalVersionAttribute("3.5.7+1.Branch.master.Sha.e432cce4a947881313f25b7211557fb3647226da")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "masstransit";
        internal const System.String AssemblyCompany = "Alexey Zimarev";
        internal const System.String AssemblyCopyright = "Copyright © 2018 Alexey Zimarev";
        internal const System.String AssemblyVersion = "3.5.7.0";
        internal const System.String AssemblyFileVersion = "3.5.7.0";
        internal const System.String AssemblyInformationalVersion = "3.5.7+1.Branch.master.Sha.e432cce4a947881313f25b7211557fb3647226da";
    }
}
